details:
  namespace: student21-bookinfo-dev
  image: ghcr.io/mrsmithz/itkmitl-bookinfo-details
  tag: dev
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8081
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: itkmitl.bookinfo.dev.opsta.net
  path: "/student21/details(/|$)(.*)"
  serviceType: ClusterIP
